[tool.black]
line_length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
remove_redundant_aliases = true

[tool.ruff]
line-length = 88
select = ["F", "E", "W", "I"]
fixable = ["F401", "E402", "E302"]