[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "HousePricingPredictor"

[tool.black]
line_length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
float_to_top = true
line_length = 88
remove_redundant_aliases = true

[tool.ruff]
line-length = 88
select = ["F", "E", "W", "I"]
fixable = ["F401", "E402", "E302"]
