name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "feature/**"

jobs:
  build:
    name: Set up Conda Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          conda-version: "24.11.2"
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Configure Conda to add 'defaults' channel explicitly
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda config --add channels defaults

      - name: Install flake8 and run pythoncode
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mle-dev
          conda install -y flake8  # Ensures flake8 is available
          flake8 nonstandardcode.py
          python nonstandardcode.py