name: Build Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Job 1 - Build the package and upload artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install tree CLI tool
      run: sudo apt-get install tree

    - name: Display directory tree before building
      run: tree -d

    - name: Build package
      run: |
        pip install build
        python -m build .
        echo "Building the package..."

    - name: Display directory tree after building
      run: tree -d

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          dist/*