on:
  push:
    branches:
      - main
      - fix/*
  pull_request:
    branches:
      - main
jobs:
  custom-installer:
    name: Ex5 Miniforge for PyPy
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env create -f env.yml
          conda activate mle-dev
          isort .
          black .
          flake8 . --count --show-source --statistics
          python nonstandardcode.py

