name: Creating docker image

on:
  push:

jobs:
  docker-job:
    name: dockerhub login, build and push image to dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/house-price-prediction:pipeline-built .

    - name: Push the Docker image to DockerHub
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/house-price-prediction:pipeline-built
  