name: Build Package

on:
  push:

jobs:
  doc-job: 
    name: Build the docs using Sphinx
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        conda-version: "24.11.2"
        environment-file: env.yml
        activate-environment: mle-dev
  
    - name: Configure 'defaults' channel explicitly in Conda and activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda config --add channels defaults
        conda activate mle-dev

    - name: Install tree CLI tool
      run: sudo apt-get install tree

    - name: Display directory tree before building the docs
      run: tree -d
    
    - name: Build Docs using Sphinx
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate mle-dev
        conda install sphinx
        cd docs
        sphinx-build -b html docs/source docs/build/html
    
    - name: Display directory tree before building the docs
      run: tree -d
    
    - name: Upload built HTML docs
      uses: actions/upload-artifact@v4
      with:
        name: docs-html
        path: docs/build/html